# Generated by Django 3.0.6 on 2020-08-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_sum',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
