# Generated by Django 3.0.6 on 2020-08-14 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_total_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
