# Generated by Django 3.0.6 on 2020-08-14 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_sum',
        ),
    ]
