# Generated by Django 3.0.6 on 2020-08-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='end',
            field=models.DateTimeField(default=0),
        ),
    ]
