# Generated by Django 3.0.6 on 2020-08-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='dur',
            new_name='film_duration',
        ),
    ]
