# Generated by Django 3.0.6 on 2020-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200808_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image_title',
            field=models.ImageField(blank=True, null=True, upload_to='media/film_images/'),
        ),
    ]
