# Generated by Django 3.0.6 on 2020-08-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200811_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='end_show',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Seance'),
        ),
    ]
