# Generated by Django 3.0.6 on 2020-08-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200813_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='seance',
            new_name='seance_id',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('seat', 'row', 'seance_id')},
        ),
    ]
