# Generated by Django 3.0.6 on 2020-08-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20200813_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='seance_id',
            new_name='seance',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('seat', 'row', 'seance')},
        ),
    ]
