# Generated by Django 3.0.6 on 2020-08-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20200813_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='sold_out',
        ),
    ]
